#!/bin/bash

if [[ "$1" == "" ]]
then
  echo "usage: inst <test1|test2|test3>"
  exit 2
fi

echo 0 > /proc/sys/kernel/nmi_watchdog
perf stat -A --all-user -o ${1}.perf --cpu=3 -d ./${1}.tsk
echo 1 > /proc/sys/kernel/nmi_watchdog
